apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dronzerclusters.dronzer.ai
spec:
  group: dronzer.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                version:
                  type: string
                plugins:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: dronzerclusters
    singular: dronzercluster
    kind: DronzerCluster
    shortNames:
    - dc
---
apiVersion: dronzer.ai/v1
kind: DronzerCluster
metadata:
  name: dronzer-prod-eu
spec:
  replicas: 5
  version: "v1.5.0"
  plugins:
    - "github_connector"
    - "playwright_engine"
