from typing import Any, Protocol, TypeVar

T = TypeVar("T")


class ICache(Protocol):
    async def get(self, key: str) -> Any: ...
    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...


class IEventBus(Protocol):
    async def publish(self, topic: str, event: Any) -> None: ...
    async def subscribe(self, topic: str, handler: Any) -> None: ...
