"""add_gateway_keys_table

Revision ID: 02720f1174a3
Revises:
Create Date: 2026-07-13 18:52:38.917491

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02720f1174a3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateway_keys",
        sa.Column("hashed_key", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gateway_keys_hashed_key"), "gateway_keys", ["hashed_key"], unique=True)
    op.create_index(
        op.f("ix_gateway_keys_is_deleted"), "gateway_keys", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_keys_organization_id"), "gateway_keys", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gateway_keys_organization_id"), table_name="gateway_keys")
    op.drop_index(op.f("ix_gateway_keys_is_deleted"), table_name="gateway_keys")
    op.drop_index(op.f("ix_gateway_keys_hashed_key"), table_name="gateway_keys")
    op.drop_table("gateway_keys")
    # ### end Alembic commands ###
