"""Add task-aware gateway keys

Revision ID: e29f56de8037
Revises: 02720f1174a3
Create Date: 2026-07-13 21:28:17.636194

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e29f56de8037"
down_revision: str | None = "02720f1174a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gateway_keys",
        sa.Column("task_type", sa.String(length=100), server_default="chat", nullable=False),
    )
    op.add_column(
        "gateway_keys",
        sa.Column("model_priorities", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "gateway_keys",
        sa.Column("provider_priorities", sa.JSON(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gateway_keys", "provider_priorities")
    op.drop_column("gateway_keys", "model_priorities")
    op.drop_column("gateway_keys", "task_type")
    # ### end Alembic commands ###
